max-players: 8
min-players: 4
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x: -197.5
  y: 72
  z: 118.5
  yaw: 90
  pitch: 0
arenas:
  0:
    spawn:
      world: 'world'
      x: -208.5
      y: 72
      z: 114.5
      yaw: -90
      pitch: 0
  1:
    spawn:
      world: 'world'
      x: -207.5
      y: 72
      z: 123.5
      yaw: -90
      pitch: 0
    world: 'world'
    teams:
      red:
        x: -207.5
        y: 72
        z: 123.5
        yaw: -90
        pitch: 0
      blue:
        x: -207.5
        y: 72
        z: 123.5
        yaw: -90
        pitch: 0
      green:
        x: -207.5
        y: 72
        z: 123.5
        yaw: -90
        pitch: 0
      yellow:
        x: -207.5
        y: 72
        z: 123.5
        yaw: -90
        pitch: 0