name: spigot-bed-wars
version: '1.0-SNAPSHOT'
main: org.radialo.spigotbedwars.BedWarsPlugin
api-version: '1.20'
authors: [RadiALo]
description: My BedWars plugin!
commands:
  arena:
    description: Arena command!